### ISSUE TITLE
[Feature Request] (Disallow|Require)YodaConditions for specific operators

### ISSUE THREAD

**Issue by Slayer95** [jscs-dev/node-jscs#1026]
I'd like to forbid YodaConditions for <code>===</code>, but allow them for numeric comparisons, so 
that the following constructs can be <i>simultaneously</i> made invalid/valid respectively:

Invalid
``if (5 === foo) {
...
}``

Valid
``if (foo === 5) {
...
}``

Valid
``if (0 <= foo && foo < 5) {
...
}``

It's aesthetically pleasing to be able to chain comparison operators like this.
This would imply that both YodaConditions rules accept arrays of operators as legal values, like this

<code>"DisallowYodaConditions": ["==", "===", "!=", !=="]</code>

**Comment by coolaj86** [comment]
Likewise I would like to require yoda conditions for `===` and `==`  because it prevents accidental assignment where comparison was intended.

However, in the case of `<`, `>`, `>=` and `<=` it's more difficult to understand and there's no safety advantage (the safety there comes from always writing it so that the condition is true to prevent unchecked vars like `null >= 3`)

**Comment by masi** [comment]
If safety/securiity is a concern than IMHO Yoda is only a must only for == (beware type juggling!). But then you could always write === and !== (which linters may force upon you anyway).

**Comment by markelog** [comment]
@Slayer95, i see you have a commit there, would you like to send us a PR?

**Comment by hzoo** [comment]
I think it's https://github.com/jscs-dev/node-jscs/pull/1031

**Comment by paulschreiber** [comment]
Is this ready to be integrated? It'd be very helpful for me.

**Comment by kilianc** [comment]
+1 on this
