### ISSUE TITLE
Issue with CLI glob pattern

### ISSUE THREAD

**Issue by necolas** [jscs-dev/node-jscs#1079]
I can't get the command below to lint JS files in 1 or more subdirectories. It only lints JS files in directories one level below `src`.

```
jscs src/**/*.js
```

**Comment by hzoo** [comment]
Hmm I'm using version 1.11.3 and both `jscs ./lib` and `jscs ./lib/**/*.js` is working

![image](https://cloud.githubusercontent.com/assets/588473/6241087/e4295a88-b6e5-11e4-822c-8366882cc276.png)

**Comment by necolas** [comment]
Try putting something in `lib/config/temp/`.

`jscs lib/` seems to work with several nested subdirs, just not the glob pattern.

**Comment by hzoo** [comment]
Ok I created the same files in `lib/config/temp/` and `lib/config/temp/temp2`

![image](https://cloud.githubusercontent.com/assets/588473/6241459/5ba4fe6e-b6eb-11e4-8d13-e57a784736c7.png)

**Comment by necolas** [comment]
Hmm, interesting.

**Comment by hzoo** [comment]
Maybe it's the package that handles the glob? Or OS specific thing?

**Comment by zxqfox** [comment]
@necolas Can you try to quote pattern?
```sh
jscs 'src/**/*.js'
```

**Comment by zxqfox** [comment]
I just think it's not a bug or something because launching from different shell can produce different results. Also double star (`**`) pattern was used in `git` and many other ignore files to mark including inner directories, but it works as single star in `bash` and `sh` and when you using it from shell `bash`/`sh` will expose it as a space-delimited list of arguments.

```sh
ls test/**/*.js | xargs echo
```

Btw looks like `fish` using double-star as you expect because I see nested directories in output. But not `bash`/`sh` ;-)
