### ISSUE TITLE
Rules should have the option to opt out of auto-fixing

### ISSUE THREAD

**Issue by TheSavior** [jscs-dev/node-jscs#1089]
Some rules use whitespace assertions but aren't trivial to fix.

For example:

```
 * disallowMultipleLineStrings
 * ##### Valid
 * ```js
 * var x = "multi" +
 *         "line";
 * var y = "single line";
 * ```
 *
 * ##### Invalid
 * ```js
 * var x = "multi \
 *         line";
 * ```
```

The rules uses 
```
errors.assert.sameLine({
                token: token,
                nextToken: token,
                message: 'Multiline strings are disallowed.'
            });
```

I think there should be another option for the assertion that is `fix: false` or `dontFix: true`.

**Comment by mikesherov** [comment]
The problem is that this rule should not be using an assertion, and the assertion it's using is a hack. 

The assertions should themselves throw if the `token` and `nextToken` are equivalent, and this rule should be updated to not use an assertion.

That way, all assertions remain trivial to fix. Wanna take this one @TheSavior ?

**Comment by TheSavior** [comment]
:+1:
