### ISSUE TITLE
requirePaddingNewlinesBeforeKeywords when returning function

### ISSUE THREAD

**Issue by SimenB** [jscs-dev/node-jscs#1124]
Hi!

I'm having a problem with the `requirePaddingNewlinesBeforeKeywords` rule when returning a function.

```javascript
Backbone.Collection.prototype.fetch = function () {
    var fetch = Backbone.Collection.prototype.fetch;

    return function () { // This line gets an error
        this.trigger('fetch');

        return fetch.apply(this, arguments);
    };
}();
```

That piece of code, JSCS wants a newline before function. But if adding it, ASI messes up everything.

In general, we want a newline before `function`, but not in this case. Do I have to locally disable that rule every place we return functions?

**Comment by mikesherov** [comment]
Thanks for contributing! This is a known issue and a duplicate. The problem is that this rule isn't really appropriate for the `function` keyword, considering you probably also don't want a newline before methods:

```
{
  prop: function() {
...
```

/cc @markelog and @mdevils as this will also be the same problem for the `while` in `doWhile` and `default` in `export default`

**Comment by SimenB** [comment]
Hmm, true enough. I'd like it here though.

```javascript
function doMagic() {
    return 'hey';
}
function doEvenMoreMagic() {
    return 'hey you!';
}
```

And assigning them to variables makes the warning go away anyways.

I'll just remove the function key from it, thanks for the swift response :smile:

**Comment by mikesherov** [comment]
Yeah, if you'd like, file a new issue for requirePaddingNewlinesBeforeFunctionDeclarations. Thanks again!

**Comment by guilhemSoulas** [comment]
+1
