### ISSUE TITLE
Appveyor: fixup tests and check work on win

### ISSUE THREAD

**Issue by zxqfox** [jscs-dev/node-jscs#1136]
Ref https://github.com/jscs-dev/node-jscs/pull/1126#issuecomment-77069354
Ref iojs/io.js#1068

**Comment by mrjoelkemp** [comment]
The history details when the first breaking build occurred: https://ci.appveyor.com/project/mdevils/node-jscs/history. That's odd, since I know that https://ci.appveyor.com/project/mdevils/node-jscs/build/156 for sure had passing checks.

I reached out to AppVeyor to see what's up: https://twitter.com/mrjoelkemp/status/573114388196028416

**Comment by mrjoelkemp** [comment]
Heard back from AppVeyor. The logs open properly in Firefox. 

You'll see 484 passing and 2697 tests failing. https://ci.appveyor.com/project/mdevils/node-jscs/build/157

**Comment by zxqfox** [comment]
I'm not sure that this is an appveyor bug. I can repeat this with 1.4.3 iojs on win7 machine. Exactly the same error set. ;-(

Btw, v1.4.3 on my linux box also fails with:
```
../deps/uv/src/unix/stream.c:1174: uv_shutdown: Assertion `(stream->type == UV_TCP || stream->type == UV_NAMED_PIPE) && "uv_shutdown (unix) only supports uv_handle_t right now"' failed.
```
on `mocha` call.

**Comment by zxqfox** [comment]
Okay, it's definitely `iojs v1.4.1+` trouble. I suggest to freeze nodejs version for appveyor to 0.12 or 0.10 and 0.12.

**Comment by mrjoelkemp** [comment]
Mind modifying the config as necessary?
