### ISSUE TITLE
Should parse errors be disabled by inline comments?

### ISSUE THREAD

**Issue by amel-true** [jscs-dev/node-jscs#1156]
E4X syntax stops further code analysis.  Inline comments doesn't work.

Unexpected token ( at /Users/melikhov/source/fastpay/etc/xscript/union/js/ctrl/debts/gibdd.js :
   163 |    /* jscs:disable  */
   164 |    userData[this[this.mainPropertyName]] =
   165 |     command.response.data.(function::attribute('type').toString() === this[this.mainPropertyName]).toString();
------------------------------------^
   166 |    userData[this.CERT_CODE] =
   167 |     command.response.data.(function::attribute('type').toString() === this.CERT_CODE).toString();

1 code style error found.

**Comment by mrjoelkemp** [comment]
Hi @amel-true. Thanks for contributing.

Parse errors aren't currently handled by inline comments. 

This test fails:

```js
    it('should suppress esprima parse errors', function() {
        var errors = checker.checkString('//jscs:disable\n\tvar x =');
        assert.ok(errors.isEmpty());
    });
```

@mikesherov Was this intentional? The esprima parse error is consumed by jscs and presented as a style error, so it seems like the parse error should be disabled by inline commenting. Thoughts?

**Comment by okonet** [comment]
+1 

This is quite annoying to not be able to disable it by inline comments.

**Comment by markelog** [comment]
E4X is deprecated - https://developer.mozilla.org/en-US/docs/Archive/Web/E4X, i'm surprised anyone still use that.

Do you have big legacy code that you support?

**Comment by amel-true** [comment]
Yep, Yandex.Money still using E4X and xscript. =)

**Comment by markelog** [comment]
For crying out loud you guys :-).

Check this out - https://github.com/jscs-dev/node-jscs/commit/8de3850aff54e1519bd196a0627ee1cc3b6a96a0, we can do the same here, would you like to submit the pull request?

**Comment by markelog** [comment]
Hm, or not, it seem it would be a pretty complicated regexps :-(

**Comment by amel-true** [comment]
Thank you. I'll try.

**Comment by markelog** [comment]
If you can't come up with that regexp then it seems we are out of options, since we use esprima as a parser, which even if you provide `tolerant` flag would not work with such code.

You could try https://github.com/Constellation/esprima, but obviously that wouldn't be best solution if it would be solution at all.

Yeah, jshint can mitigate that, but it uses its own parser, so they could do pretty much whatever they want. ESLint can't, because they do what we do.

Only one viable solution that i can think of is to parse js line by line, which has it own drawbacks in terms of great degree of complication.

**Comment by hzoo** [comment]
Going to close this issue in favor of https://github.com/jscs-dev/node-jscs/issues/1655 since it's the same?
