### ISSUE TITLE
Possible Auto-configure enhancements?

### ISSUE THREAD

**Issue by ariutta** [jscs-dev/node-jscs#1170]
Hello,

The auto-configure feature (#797) is a great idea. It would be useful if the ```exception``` option allowed for choosing an alternate value instead of just setting the rule to ```null```. Even better would be if the number of errors for each possible alternate value were shown.

I have [code](https://github.com/ariutta/jscs-auto-configure/blob/master/test/manual-tests/create.js) for generating a .jscsrc file by automatically choosing the rule value that produces the lowest error count. It doesn't have any command line options yet. Would there be interest in integrating something like this as a built-in option for JSCS?

**Comment by mrjoelkemp** [comment]
Hey @ariutta. Thanks for contributing.

> It would be useful if the exception option allowed for choosing an alternate value instead of just setting the rule to null. 

I'm not seeing the benefit to allowing users to supply custom values in the autoconfig prompt. It's the same as replacing null with another value in the generated jscsrc. The goal of autoconfig, was to get the user up and running as quickly as possible. We also envision replacing the "fix it yourself" with "fix it automatically" so that you wouldn't have to worry about configuration.

> Even better would be if the number of errors for each possible alternate value were shown.

This heavily depends on #480 to avoid having to modify rules and the autoconfigure code. 

> I have code for generating a .jscsrc file by automatically choosing the rule value that produces the lowest error count.

Great work here. Along with my previous comment, the route you've experimented with relies on us hardcoding the rule values in both the rule definition and the autoconfigure code.

> Would there be interest in integrating something like this as a built-in option for JSCS?

Definitely, so long as it read the rule values from the rule's definition.

**Comment by ariutta** [comment]
Great. I'll keep my eye on #480. When it's done, I'll see if I can get time to add this.
