### ISSUE TITLE
v1.12.0 bug: disallowIdentifierNames rule disallows `toString`, `valueOf`, `propertyIsEnumerable`, `__proto__`

### ISSUE THREAD

**Issue by ljharb** [jscs-dev/node-jscs#1203]
I'm explicitly passing `[]`, and it's disallowing `toString`, `valueOf`, `__proto__`, `isPrototypeOf`, `constructor`, `toLocaleString`, and `propertyIsEnumerable` in my projects.

I'm not sure exactly why, but perhaps the way you're iterating the `identifiers` array is incorrect - perhaps you're iterating over the entire prototype, instead of just own properties, or using `Array#forEach`?

**Comment by ljharb** [comment]
This is basically a breaking change in a minor bump, so hopefully it can get resolved very soon.

**Comment by mrjoelkemp** [comment]
Thanks for reporting.

It's a new rule (which is opt in), so it's not a breaking change - just a
bug.

Will fix soon.

**Comment by hzoo** [comment]
That's interesting haha... so `disallowedIdentifiers` is an object and the loop adds propertys to the object based on the array you pass (so with `[ ]` is an empty object).
Since we check `if (disallowedIdentifiers[node.name])` then it becomes `disallowedIdentifiers['toString']` and becomes a property access of the object and then becomes the actual function of `obj.toString` which is truthy and results in the error.

We can explicity check for true `=== true`) and it should work.

**Comment by mrjoelkemp** [comment]
:+1: thanks @hzoo

**Comment by TheSavior** [comment]
@hzoo, I believe this is the case where you would use `hasOwnProperty` which just doesn't check the prototype.

**Comment by mikesherov** [comment]
`hasOwnProperty` is the correct solution here.

**Comment by hzoo** [comment]
ok will update the PR

**Comment by ljharb** [comment]
Or better, `Object.keys(obj).forEach(function (key) { obj[key] })` - loops are silly :-)

**Comment by ljharb** [comment]
Thank you!!! I'll wait quietly for the publish :-)
