### ISSUE TITLE
Removal of `JsFile.prototype.getTokenPosByRangeStart`

### ISSUE THREAD

**Issue by rwjblue** [jscs-dev/node-jscs#1214]
`JsFile.prototype.getTokenPosByRangeStart` was removed in https://github.com/jscs-dev/node-jscs/pull/1076. Since `JsFile` is exposed as public API and this function was not marked as `@private` (or underscored), I would have expected it to be available (but possibly deprecated) throughout the 1.x timeframe.  I also did not see this removal mentioned in the [release notes](https://github.com/jscs-dev/node-jscs/releases/tag/v1.12.0).

We were using this function in a custom rule in Ember ([here](https://github.com/emberjs/ember.js/blob/master/lib/jscs-rules/require-spaces-after-closing-parenthesis-in-function-declaration.js)), and an issue was reported in https://github.com/emberjs/ember.js/issues/10743.

I have updated the rule in Ember to allow builds to work properly (in https://github.com/emberjs/ember.js/pull/10747), but I am uncertain what y'alls normal process is here for this type of stuff so I figured I'd open an issue to let y'all know.

**Comment by rwjblue** [comment]
Also, the newer `getFirstNodeToken` method is **much** better/easier to use,  thank you for adding it.

**Comment by hzoo** [comment]
There was an issue about this - I think https://github.com/jscs-dev/node-jscs/issues/1084? Sorry about that

**Comment by mrjoelkemp** [comment]
Thanks @hzoo. Sorry about that oversight @rwjblue; we removed the function since it wasn't being used internally. We should have deprecated it and removed it in 2.0. Thanks for reporting the issue; it's great to get some certainty that folks are using the public apis.

@mikesherov Should we consider reverting the commit that removes the JSFile method and including it in a patch release?

**Comment by markelog** [comment]
I would even move those methods in different repo as its own module. 

Since this no longer fictional, i would re-added, who knows when 2.0 will came up.

**Comment by mikesherov** [comment]
Not interested in readding the removed functions. We have never documented them. Yes, it's unfortunate that people had relied on them but we'd need to document their existence before considering them part of the API.

**Comment by mrjoelkemp** [comment]
> it's unfortunate that people had relied on them

Doesn't that potentially affect all users of `additionalRules`? Not that everyone used this particular function, but they use JSFile's methods.

This feels like a delicate area to be so firm. By this logic, we could merge the rule of silence PR since we never documented that the error/success messages couldn't change – well knowing 3rd party integrations probably rely on that output. 

> we'd need to document their existence

Where? Within one of the markdown files?

**Comment by zxqfox** [comment]
@rwjblue Since you are the one who used in atm I have another idea: can you try to readd it on your level? Just something like:
```
// temporary readded since it was removed in jscs
require('jscs/lib/js-file').prototype.getTokenPosByRangeStart = function(start) {
    return (this.getTokenByRangeStart(start) || {})._tokenIndex;
},
```

**Comment by mikesherov** [comment]
@rwjblue if you want help using the new API instead, let me know.

**Comment by rwjblue** [comment]
@zxqfox - Yeah, that definitely works.

@mikesherov - Thank you, that is very kind! I had updated Ember's custom rule to use the new API's before (or just after?) raising this issue.

My intent here was mostly to make sure y'all knew about the potential problem for rule authors, and so that you could collectively decide how to handle removal of methods from (possibly inadvertently) public classes.

**Comment by zxqfox** [comment]
@rwjblue Thank you for that ;-) We definitely should do it and trying to describe public API for `JSFile` in #1084

**Comment by mikesherov** [comment]
OK, closing as resolved then for now.
