### ISSUE TITLE
Is there a way to use jscs with babel?

### ISSUE THREAD

**Issue by moroshko** [jscs-dev/node-jscs#1270]
I wonder if there a way to use jscs with babel 5.0?

**Comment by zxqfox** [comment]
Well you need a parser that will make Parser API AST. And the problem here is there are no stable standard for parsing ES6.

Moreover JSCS using some custom features (undescribed in standard), e.g. for handling comments. These features are specific to Esprima (the main parser that we using and supporting). It's not so important as primary parsing ES6 but keep it in mind too.

**Comment by moroshko** [comment]
@zxqfox Are you saying that JSCS has no plans moving from esprima to Babel? I noticed that [Facebook are deprecating esprima-fb](https://github.com/facebook/esprima/issues/111) and switching to Babel. I wonder what is the best way to use JSCS with JSX and ES6?

**Comment by zxqfox** [comment]
@moroshko Nope. Just saying that parser should be compatible with Parser API AST.

That's the first time I see Babel actually. Sorry for that ;-(

Earlier we used an esprima-fb and all was just fine (almost).

/cc @mikesherov @hzoo @mrjoelkemp

**Comment by zxqfox** [comment]
Folks, I think we need to rethink our JSFile (as a flexible abstraction under changing world) to support, let's say, jsfile-esprima, jsfile-acorn, jsfile-babel, etc.. JSFile itself will provide an API (as it does now) and just proxy to any AST-compatible parser. In that way we won't be damaged by any deprecations.

Perhaps it's an overengineering. ;-)

**Comment by hzoo** [comment]
Yeah currently we only support being able to passing in a different esprima version (such as `esprima-fb` or harmony). I didn't know about the deprecation, but I see that was recent!

Have we already talked about supporting other parsers like acorn?

> There may come a day soon where all of the ASTs are completely interchangeable.

From that I would say probably since there would be no differences?

@mikesherov would have a better idea since he is working on esprima/ESTree.

**Comment by zxqfox** [comment]
@hzoo I want to hear @mikesherov since he are very close to Esprima now. ;-)

The last time we talked about it (about a year ago) we agreed that we don't need anything else. Now we have JSFile and ES7 features. Looks like it's a time to rethink.

**Comment by zxqfox** [comment]
@hzoo Just fyi: Acorn had an mimic option a year ago and was an Esprima compatible AST builder. But it was a year ago ;-)

**Comment by mikesherov** [comment]
I'm not sure I've heard a single reason to move away from Esprima here?

**Comment by ariya** [comment]
Also, people easily confuse esprima-fb vs esprima. The former, what Facebook deprecated, is probably better characterized as `jsxparser`, i.e. an ES6+ parser that has some elements of Facebook's own JSX. 

As for the latter, take a look at https://github.com/jquery/esprima/issues/1099 and Esprima 2.x is steadily covering those ES6 features.

**Comment by zxqfox** [comment]
@mikesherov Not sure, lol.

@ariya Thanks!

Drawing a map to Esprima 2.x?

**Comment by hzoo** [comment]
I don't think there's any reason to move away from Esprima. One question is if we want to support another parser (Babel/acorn) if they want to use JSX or features that esprima doesn't current support at the moment (ES7) since `esprima-fb` is being deprecated later.

**Comment by moroshko** [comment]
So, what is the currently recommended way to use JSCS with JSX and es6/7?

**Comment by markelog** [comment]
Sorry for waiting (@zxqfox, @mikesherov little help you guys?)

> JSX

http://jscs.info/overview.html#-esprima-

> es6/7

http://jscs.info/overview.html#esnext

When esprima 2.3 will came out `esnext` would be enabled by default

**Comment by markelog** [comment]
FYI, i think we need to support jsx by default.

/cc @mdevils

**Comment by ben-ng** [comment]
Chiming in with a :+1: 

I've been running into issues with esprima-fb throwing errors on good code. Tried shoehorning acorn into jscs but that didn't work -- looks like jscs depends on esprima-specific features.

First-class support for JSX would be great!

**Comment by markelog** [comment]
Created https://github.com/jscs-dev/node-jscs/issues/1294

**Comment by hzoo** [comment]
So I think I've got jscs working with babel (by modifying `babel-eslint` for jscs a bit). Haven't tested that much or anything.

So you could use a modified version of that and do in your `.jscsrc`: `  "esprima": "./node_modules/babel-jscs",` assuming it's called `babel-jscs`.

**Comment by mrjoelkemp** [comment]
@hzoo Should we consider forking babel-eslint as babel-jscs, putting in the org, making the edits necessary for our purposes, then publishing the package as babel-jscs?

**Comment by hzoo** [comment]
Yeah we could if anyone thinks it could be an option. @sebmck?

After a lot of tinkering I ended up just having to change it so that it would patch `estraverse` like `babel-eslint` does. Oh also added more types to be 'Punctuator' to fix some errors since some `node.type` ends up as `TokenType` instead.

**Comment by TheSavior** [comment]
With the support from the community and large companies really rallying behind acorn / babel as the forward looking parser for es6, es7, and jsx I'm concerned about sticking with esprima / espree

**Comment by mikesherov** [comment]
We rely on the token output of Esprima. There really needs to be more standardization work done around the concrete aspects of the AST, which we are actively discussing in the ESTree repo.

Once we standardize on that, the discussion about acorn/babel/esprima/Espree becomes irrelevant because they'll all produce equivalent output that JSCS expects.

In the meantime, I'd like to avoid modifying JSCS to accomodate the different formats. If someone wants to make an adapter that converts acorn/babel output to match Esprima, and then provide that as a custom parser, great.

Also, we should be working to have JSCS take in a serialized AST or an AST in memory as input so that JSCS doesn't even have to do parsing if another tool has already done it.

Again, the problem lies in the fact that we rely on the non-standardized portion of the AST.

Esprima is also under active development, and had support behind it as well, (full disclosure: I'm on the Esprima team), and is in active discussions with Acorn and Babel around standardization. Esprima also is almost at full ES6 support and has plans soon thereafter to provide plugin support for JSX.

**Comment by hzoo** [comment]
Thanks @mikesherov. I'm thinking it would just be another parser option. To use it we can just plug it in as another `"esprima"` so no JSCS changes should be necessary. `babel-eslint` has a [acorn-to-esprima.js](https://github.com/babel/babel-eslint/blob/master/acorn-to-esprima.js).

**Comment by hzoo** [comment]
I guess we can close this in favor of #1353?
