### ISSUE TITLE
New Rule: requireSpread (ES6)

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1326]
Could this work?

Similar to #1305 (`requireRest or disallowArgumentsObject`)

```js
// Good
const wrap = (f, g) => (...args) => g(f, ...args)
instance.method(...args)

// Bad
const wrap = (f, g) => (...args) => g.apply(g, [f].concat(args))
instance.method.apply(instance, args);
```

**Comment by mikesherov** [comment]
We can always make sure that the first parameter is the same as the object of the member expression.

```
// bad 
g.apply(g, arguments);
```

```
// good, we can't be certain that apply is Function.prototype.apply
g.apply(arguments);
```

```
// good
g(...args);
```

**Comment by hzoo** [comment]
Thanks - sounds good.

**Comment by mzgol** [comment]
Apply is not everything; I'd like to have the following:
```js
function f() {
    return arguments[0];
}
```
banned as well so that there is no single `arguments` in my code (maybe except when it's used as a regular, non-special variable but I don't care too much about it).

But since this example should be replaced by:
```js
function f(a) {
    return a;
}
```
& there is no spread there, maybe it's not sth meant for this rule.

**Comment by hzoo** [comment]
I think that could be covered in #1305 with `disallowIdentifierNames: ['arguments']`
