### ISSUE TITLE
Improve integration with jsdoc plugin

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1531]
See https://github.com/jscs-dev/node-jscs/pull/1526 discussion

**Comment by leotm** [comment]
Just wondering why `"plugins": ["jscs-jsdoc"]` was removed from the *.jscsrc*, since the extension is a current requirement with the inclusion of the `"jsDoc"` rules? Cheers

**Comment by zxqfox** [comment]
I think we should move out jsdoc rule from default rules and add it with some other way.

Also what you thinking about rewriting default rules instead of throwing an errors? Atm we can't use another version of jsDoc rule. Would be nice to use rule from plugin instead of bundled one if we want it (e.g. via `"plugins": ["jsdoc"]`).

**Comment by markelog** [comment]
> I think we should move out jsdoc rule from default rules and add it with some other way.

Yeah, that is the idea :-).

> Also what you thinking about rewriting default rules instead of throwing an errors? 

I think we should take one step at the time, this might be confusing for user though.

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
