### ISSUE TITLE
Be able to consume an AST/CST as input into JSCS

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1642]
So instead of parsing the js file again, read the AST as input from another tool that can produce an AST which would help with speed/integration with others.

**Comment by markelog** [comment]
What is the use-case? How it would work with CST?

**Comment by hzoo** [comment]
It's mostly a speed thing if another tool is already doing the parsing - https://github.com/jscs-dev/node-jscs/issues/1270#issuecomment-99816879. Lets us potentially interop better with another tool?

@thejameskyle talks about this stuff in a talk https://www.youtube.com/watch?v=Ku3AWp_-Qzs&feature=youtu.be&t=9m22s

**Comment by mrjoelkemp** [comment]
In theory, it's a great idea. However, it feels like a solution in search of an integration. 

1. None of our integrations have requested this. 
2. The perf gains only arise when you'd otherwise redundantly parse really large files (like 3rd party libs that likely shouldn't be linted) but they're still only saving a few hundred ms in aggregate once vendor libs  are excluded.

> How it would work with CST?

We'd need an AST to CST converter if the user pipes in an AST (assuming the CST structure can be extrapolated from an AST). Without a CST being a json structure, you can't pipe it. 

Surely the ESTree folks have had lengthy discussions on this – which is why they're pushing for the JSON-formatted CST.
