### ISSUE TITLE
Enhancement: Update configuration option

### ISSUE THREAD

**Issue by hzoo** [jscs-dev/node-jscs#1708]
This would be similar to autoconfigure (which can be run when you first start using JSCS). Or it could replace the original functionality when we check that a preset/config is already being used.

So instead of running each preset against your codebase, it would run over rules that you didn't enable. (or newer rules you haven't enabled since the latest release). Depending on how many errors (or 0), it would prompt the user to add it to the config. And maybe it would explicitly put all the rules in the config except leave them null if it's disabled.

**Comment by alawatthe** [comment]
I really like the idea. :-)
I would show all rules which are not enabled, not only the new rules from the last release. Since this is easier to maintain, and from a user perspective, it is weird if I missed a release.
Furthermore I would list all the rules, independent of how many errors they produce. Because if a rule is not enforced, it is very likely that it fails a lot.
For some rules e.g. disallowSpaceAfterBinaryOperators it would be cool, if this could check if every operator is either in this rule or the dual rule.
