### ISSUE TITLE
Non-stylistic rules

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#1771]
Do we want it? It seems we are slowly getting to that point.

We could implement our own rules or use eslint/jshint/jslint as a dependency using their own set of rules or both.

With "dependency" approach, we would need to figure out bridge to it and settle on documentation issues.

/cc @nzakas, @rwaldron, @mdevils

**Comment by hzoo** [comment]
Not sure exactly what should be done but :+1: for better integration of tools at least.

ESLint can consume/pass ASTs http://eslint.org/blog/2015/08/eslint-v1.3.0-released/#using-asts-with-the-nodejs-api

**Comment by ronkorving** [comment]
Why bother complicating things? I already use ESLint for safety checks and JSCS for style checks. I'm absolutely fine using 2 tools for 2 different purposes. I don't need them mixed up. Next year, someone will make "ESLint 2000 Pro" and I may want to use that instead of ESLint. That should have no impact on how I use JSCS.

The *only* added value I can see is sharing ASTs, so performance could be boosted. But then I would suggest releasing a module that parses a file's AST and then passes it through a JSCS API and an ESLint API. At least then you're not creating dependencies between ESLint and JSCS.

**Comment by mrjoelkemp** [comment]
That's the ideal usage: use jscs for style checks and another linter for
other linting needs.

Honestly, it's painful to see communities reinventing the wheel when it
comes to linting rules. Everyone loses when we stall progress implementing
the same features across numerous tools (eslint, babel, esformatter).

We've heard from the eslint community and our own that folks like the
convenience of one tool that covers linting needs. We have the machinery to
do non-style rules already but have punted those rules to eslint for
semantic adherence.

To my earlier point about not duplicating effort, using eslint as a
dependency makes most sense.

If most of the parties are in agreement, then we can list out the problem
areas bridging the two tools.

**Comment by ronkorving** [comment]
I'm glad you don't want to reinvent the wheel. But what's the purpose of adding ESLint as a dependency at all? Do people really want to deal with a single tool, period? It's not gonna make configuration any easier (documentation will still be split) and if I want to upgrade ESLint to the latest release, I'm now stuck waiting for JSCS to be updated first. This adds negative value to me as a user, I see nothing positive about it.

Again, if people want 1 tool so badly, why not make a separate package for this that has both ESLint and JSCS as a dependency? Why clutter the jscs code base?

Just my 2 cents, coming from a long time fan and user of jscs.
