### ISSUE TITLE
Add in the website's documentation of a rule, the rational for said rule 

### ISSUE THREAD

**Issue by allan-simon** [jscs-dev/node-jscs#1884]
Especially for new comers in a team, it may be easier to embrace/accept a coding style rule if you know what kind of mistakes this rule protect you against

for example http://jscs.info/rule/disallowAnonymousFunctions ,  what kind of bug/problem may emerge if I use anonymous function ?

**Comment by hzoo** [comment]
Thanks for reporting the issue - yeah we need to improve the docs more. If you want to make a PR for it go ahead! The reason naming a function would be to have a better stack trace when there's an error - however it doesn't help when you decide to use arrow functions (ES6) which are always anonymous so that would be on the browers/node to provide better errors I think.

**Comment by Nargonath** [comment]
I'll try to submit a PR ASAP if that's ok.

**Comment by Nargonath** [comment]
Thank you for accepting the PR and for doing the "beginner-friendly" label. It was my first time contributing to OpenSource.

**Comment by markelog** [comment]
Congrats!

**Comment by allan-simon** [comment]
@Nargonath  : awesome, keep contributing like that :) :+1:

**Comment by Qix-** [comment]
@Nargonath :+1: Welcome!

**Comment by Nargonath** [comment]
Thanks guys!
