### ISSUE TITLE
requireObjectKeysOnNewLine

### ISSUE THREAD

**Issue by ficristo** [jscs-dev/node-jscs#1898]
I would like to enable requireObjectKeysOnNewLine rule but for my needs it should work a little differently.
If all the keys are on a single line is valid, otherwise every key should be on a new line.
```javascript
// Valid
var obj = {a: 0, b: 1, c: 2};
// Valid
var obj = {
  a: 0, b: 1, c: 2
};
// Valid
var obj = {
  a: 0,
  b: 1,
  c: 2
};
// Invalid
var obj = {
  a: 0, b: 1,
  c: 2
};
// Invalid
var obj = { a: 0, b: 1,
  c: 2
};
```

**Comment by hzoo** [comment]
I was going to say it would be a new option but it just sounds weird if the rule is `requireObjectKeysOnNewLine`? Maybe it should be a new rule?

Could be an option `"allExcept": "sameLine"`. Would you like to make a PR? Most of the team will be busy working on 3.0 issues instead of adding new rules/options.
