### ISSUE TITLE
error loop regarding javasript object in array

### ISSUE THREAD

**Issue by clementmiao** [jscs-dev/node-jscs#1915]
Error rendered by [linter-jscs](https://github.com/AtomLinter/linter-jscs) Atom text editor library, but believe the problem is node-jscs.

Below is a screenshot of the issue I was having, where it indicates to me that there is a missing comma before closing beracket.

![image of issue](https://www.dropbox.com/s/2owvt0sh4l4lhrm/Screenshot%202015-10-22%2022.33.25.png?dl=1)

So I added the the missing comma, so that line 10 has the error fixed:
![image of step 2](https://www.dropbox.com/s/nqfhdpu78tit66t/Screenshot%202015-10-22%2022.35.53.png?dl=1)

I then get a second error, 'Space required after comma', as indicated.

Once I fixed that, I get the last error:
![last error](https://www.dropbox.com/s/9vqvnsqr2bkl0j5/Screenshot%202015-10-22%2022.37.27.png?dl=1)

As you can see, this is a loop of errors since I remove the space, I get back to the second error.

Let me know if it's a user problem.

**Comment by cybermerlin** [comment]
last comma - bad taste

**Comment by hzoo** [comment]
Mostly likely requireSpaceAfterComma needs an exception if it's a trailing comma cc @bjdixon if you want to look at it or I can

**Comment by bjdixon** [comment]
@hzoo I will look at this. 

I think the default behavior of not excepting trailing commas should still be fine as this condition seems to appear when combining the 3 rules (requireSpaceAfterComma, requireTrailingComma, disallowSpacesInsideArrayBrackets).

My suggestion would be to add a configuration option to exceptTrailingCommas. eg: ``` "requireSpaceAfterComma": "exceptTrailingCommas" ``` Let me know if this isn't what you had in mind otherwise I'll submit a PR using this approach.
