### ISSUE TITLE
--fix option removes escaped backticks in ES6 template strings

### ISSUE THREAD

**Issue by dhritzkiv** [jscs-dev/node-jscs#2015]
Original code:
```js
const string = `string with \`back ticks\``;
```

"Fixed code"
```js
const string = `string with `back ticks``;
```

jshint@v2.7

**Comment by markelog** [comment]
Would you mind running `jscs --verbose`, without the `--fix` flag and posting the result? Your `.jscsrc` config would also be helpful.

> jshint@v2.7

You meant jscs, right?

**Comment by dhritzkiv** [comment]
I've narrowed down the conditions that cause this behaviour:

When the code is free of style errors, running `jscs --verbose .` returns nothing, and running `jscs --fix .` has no effect.

When I deliberately introduce an error, e.g. a trailing whitespace (tab character), then running `jscs --verbose .` results in:

```sh
disallowTrailingWhitespace: Illegal trailing whitespace at ./routes/creations.js :
   788 |
   789 |  if (!eligibleMeshAndArchiveFormatsRegex.test(format)) {
   790 |   return next(new httpErrors.BadRequest(`Invalid format value: \`${format}\``)); 
------------------------------------------------------------------------------------------^
   791 |  }
   792 |


1 code style error found.
```

Which is correct.

Then, running `jscs --fix .` fixes the whitespace, but it also strips the escaped backticks. More interestingly, it strips the backticks in several parts of the file (not just the line with the bad style).

[I've attached my `.jscsrc` file as a .zip](https://github.com/jscs-dev/node-jscs/files/58752/default.jscsrc.zip)

---

>> jshint@v2.7

> You meant jscs, right?

Derp. yes.

**Comment by markelog** [comment]
Having troubles opening that archive, would you mind posting your config to https://gist.github.com/

**Comment by dhritzkiv** [comment]
Not sure why the zip didn't work… in any case, here's the [.jscsrc gist](https://gist.github.com/dhritzkiv/96e5d19e2e0e661e2497)

**Comment by markelog** [comment]
Yeah, it is a babel (enabled when `esnext` option is used) issue :/, it removes the backslash - http://astexplorer.net/#/658X2gkWBg from tokens, whereas esprima (enabled when `esnext` is not used) do it correctly - http://astexplorer.net/#/aKoWHrenCG.

You can trying to remove `esnext` option from your config, `esprima` support most of the es6 features nowadays, but still might be incomplete.

Created an issue in the babel bug tracker - https://phabricator.babeljs.io/T6833.
@hzoo can you draw attention to this issue?

Since there is nothing we can do on our side, i'm closing it

**Comment by dhritzkiv** [comment]
Thanks!
