### ISSUE TITLE
--exctract *.html not working

### ISSUE THREAD

**Issue by aemonge** [jscs-dev/node-jscs#2123]
Hi I've tried to launch jscs with the exctract option, but it isn't working:

``jscs --extract *.html ``  nor setting the **.jscsrc** to:
```json
{
  "extract": ["*.htm", "*.html"]
}
```

I'm still getting the following:
```bash
Unexpected token < at web-component.html :
     1 |<link rel="import" href="../polymer/polymer.html">
```

**Comment by lahmatiy** [comment]
@aemonge  I'm not sure, but probably it's a html parse error. Could you provide complete source of the problem file?

**Comment by aemonge** [comment]
@lahmatiy Sure !!!

**cat cc-dm.html**
```html
<link rel="import" href="../polymer/polymer.html">
<link rel="import" href="../dataproviders-il/cc-dp-baseload.html">


<dom-module id="cc-test">
  <template>
    <h1> Hello world </h1>
  </template>
</dom-module>

<script type="text/javascript">
Polymer(function() { //Create a own scope to store the private functions ;)
  /* global _, moment */
  return {
    /**
    * The element tag name
    * @public
    */
    is: 'cc-test',

    behaviors: [
    ],

    /**
    * The element/class public and private properties.
    * @public
    */
    properties: {
    },
  };
}());
</script>
```

**cat .jscsrc**
```json
{
  "extract": ["*.htm", "*.html"]
}
```

**command**
```bash
λ datamanagers-us → jscs test.html                                                                 λ git develop|… →
Unexpected token < at test.html :
     1 |<link rel="import" href="../polymer/polymer.html">
---------^
     2 |<link rel="import" href="../ilas/cc-ilas.html">
     3 |
```

**Comment by aemonge** [comment]
**And versions**

```bash
 jscs --version                                                                 λ git develop|… →
2.10.1
```

**Comment by krave1986** [comment]
Excuse me if I am out of the topic.
I am completely fresh to javascript code world and my question is: what is --extract option supposed to do when I run jscs command line or in sublime text 3 with sublime linter and sublimeLinter-jscs installed?

I have a html file and the code is very simple:
`<!DOCTYPE html>
<html>
	<head>
		<script type="text/javascript" src="../../react-0.14.7/"></script>
		<title>react test</title>
	</head>
	<body>
		<div id="intro"></div>
		<script type="text/babel">
			React.render(
				<h1>Hello, world</h1>,
				document.getElementById('intro')
			);
		</script>
	</body>
</html>`

Then I ran the command below and nothing happend
`jscs src --esnext --extract *.html`
Is this the correct behavior with --extract option because there is nothing wrong in my code?

What about linting in sublime text with a .jscs file exact same as @aemonge 's? 
Should sublimeLinter show some hints on my html file view?

Just confused about how to make --extract option help me during programming.

**Comment by krave1986** [comment]
Excuse me if I am out of the topic.
I am completely fresh to javascript code world and my question is: what is --extract option supposed to do when I run jscs command line or in sublime text 3 with sublime linter and sublimeLinter-jscs installed?

I have a html file and the code is very simple:

```
<!DOCTYPE html>
<html>
    <head>
        <script type="text/javascript" src="../../react-0.14.7/"></script>
        <title>react test</title>
    </head>
    <body>
        <div id="intro"></div>
        <script type="text/babel">
            React.render(
                <h1>Hello, world</h1>,
                document.getElementById('intro')
            );
        </script>
    </body>
</html>
```

Then I ran the command below and nothing happend
`jscs src --esnext --extract *.html`
Is this the correct behavior with --extract option because there is nothing wrong in my code?

What about linting in sublime text with a `.jscsrc` file exact same as @aemonge 's? 
Should sublimeLinter show some hints on my html file view?

Just confused about how to make --extract option help me during programming.

**Comment by dickp** [comment]
I've just run into this issue too.

There are two related problems:

1) If the html file you want to check is in a sub directory (relative to basePath (which can be set through configPath, but that seems to be undocumented)), your extract pattern should be '**/*.html'.  This is due to the minimatch matcher being configured with path.resolve (basePath, extractPattern).

2) The scripts are only extracted when jscs is run recursively on directories.  The file/string checker doesn't handle script extraction at all.  This is a bit of a problem when trying to use gulp-jscs, as that only handles files.

If noone is working on a fix for point 2) then I'll look at creating a PR, as that's a bit of a show-stopper for me.

**Comment by dickp** [comment]
Crap.  Markdown ate the most important part of that comment.

The extract pattern should be `'**/*.html'`

**Comment by aemonge** [comment]
@dickp That would be greatly appreciated !!!! I switch to eslint and jshint, as a poor workarround

**Comment by markelog** [comment]
At this point only major and CST related bugs will be fixed.
