### ISSUE TITLE
Weird behavior of validateIndentation - emptyLines

### ISSUE THREAD

**Issue by jblandry** [jscs-dev/node-jscs#2218]
Hi,

I'm using jscs 3.0.1 on both and I get a weird behavior via `gulp-jscs` and `SublimeLinter-jscs`.

If I declare the `emptyLines` flag on `validateIndentation` I get an error on `gulp-jscs` of  bad indentation on empty lines but not in Sublime Text.

If I don't declare the `emptyLines` flag (which should be the same) I get the error in Sublime Text but not in `gulp-jscs`.

**Comment by markelog** [comment]
@mdevils could you check it out?

**Comment by richadr** [comment]
I can't speak for the sublime plugin, but I'm using jscs v3 from the command line.  `gulp-jscs` is stuck on jscs v2 (see its package.json), while a bug was fixed in jscs v3.

The bug was in the following line in the source for the rule checker:
(v2) `this._includeEmptyLines = options.allExcept.indexOf('emptyLines') > -1;`
(v3) `this._includeEmptyLines = options.allExcept.indexOf('emptyLines') === -1;`

Solution for gulp-jscs is to upgrade to v3.

**Comment by markelog** [comment]
Thanks for clarifying

**Comment by jblandry** [comment]
Thanks !
