### ISSUE TITLE
Remove "no-colors" option

### ISSUE THREAD

**Issue by markelog** [jscs-dev/node-jscs#275]
It's duplicate and needless, this matters should be deal with through `tty` module.

It would be a incompatible change, so it should be done in major release.

**Comment by jbnicolai** [comment]
@markelog @sindresorhus [`Chalk 1.0.0](https://github.com/sindresorhus/chalk/releases/tag/v1.0.0) has just been released.

> is that possible to disable auto-detection of tty? Would you accept a PR for that?

This is now possible. See this line from the release notes:
> * Add ability to force color by setting the FORCE_COLOR environment variable.

And the second, previous, issue:

> But in order to preserve current logic, we would need to change chalk.enabled value every time explainError method is called to the value of that argument, which mean it would have a side effect which it did not have before, since it would change state of chalk module.

This too has now been fixed! Rather than globally enabling and disabling the chalk module, it can now be set on a per-instance basis:

> * Ability to disable/enable colors on a per instance basis, rather than globally.

Would you be interested in picking up the move to chalk again?

**Comment by mikesherov** [comment]
@jbnicolai, I'd be interested if there was a pull request re-using it. What we have now works, but would love to be able to offload that to chalk, it's just that the core team at the moment has other priorities... So yeah, if there's a PR to reuse chalk, we'd love to use it :-)

**Comment by jbnicolai** [comment]
@mikesherov I'll see what I can do :)
