### ISSUE TITLE
Auto formatting API and option. [$315]

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/node-jscs#516]
JSCS should have the ability to automatically format a given file with the specified rules. There are several challenges here:

For now, we are only going to consider whitespace changes. This approach is outlined here:

1. Change all rules to use the JsFile traversal methods instead of directly referencing the token by index directly. This allows us to change the underlying token data structure at will while only having to change the traversal methods.
2. Make all whitespace only rules use the token-assert framework.
3. Modify the token list so that it includes comment tokens, and a new terminal token called "EOF".
3a. Modify traversal methods to ignore comment tokens as necessary.
4. Modify comment tokens to include a property called "prefix", which contains the preceding whitespace.
5. Add a function called errors.fixToken (or some other name), which takes in a token, and the updated prefix whitespace, which modifies the prefix of that token.
6. Make token-assert call errors.fixToken appropriately.
7. Modify StringChecker so that it can output the modifed source and save it to disk. It's simply a loop over the token list, printing the prefix followed by the value of the token.
8. Modify CLI to respect a `--fix` parameter, which triggers the autoformat option.

Please see https://github.com/mdevils/node-jscs/pull/514 as one possible implementation that ultimately wasn't how we wanted to approach the problem.

**Comment by jzaefferer** [comment]
So #751 was merged, introducing the infrastructure for autofixing, but not the autofixing itself, is that right? Does someone have plans to work on the next step? If not, would a bigger bounty make a difference?

**Comment by mikesherov** [comment]
Yes, it's the next thing im working on. Bounty makes no difference here.

**Comment by indexzero** [comment]
That's awesome @mikesherov! I didn't realize #752 was merged. Is there a running list of rules that need formatters? Now that the API is defined I could help write a few.

**Comment by soliton4** [comment]
hi there
i found this in my inbox:
https://github.com/soliton4/nodeMirror/issues/18

would be a totally cool feature, but it looks like the formatting option is still under construction.
is there any part of it usable and can you point me to a working piece of code?

i basically need the option to input text and get formated text as output.

thank you very much ;D

**Comment by jdlrobson** [comment]
Hey @mikesherov I'm super interested in this too. Is there any branch I should be watching where this is happening? I would be interested to see how you are thinking about this and see if I can help out!

**Comment by mikesherov** [comment]
@jdlrobson and @indexzero, the most helpful thing you can do is review all existing rules and make sure spacing and line break rules are all using the `file.assert` methods. Those will be the first to get fixed.

**Comment by mikesherov** [comment]
Just updated the description with full outline of the approach:

1. Change all rules to use the JsFile traversal methods instead of directly referencing the token by index directly. This allows us to change the underlying token data structure at will while only having to change the traversal methods.
2. Make all whitespace only rules use the token-assert framework.
3. Modify the token list so that it includes comment tokens, and a new terminal token called "EOF". 
3a. Modify traversal methods to ignore comment tokens as necessary.
4. Modify comment tokens to include a property called "prefix", which contains the preceding whitespace.
5. Add a function called errors.fixToken (or some other name), which takes in a token, and the updated prefix whitespace, which modifies the prefix of that token.
6. Make token-assert call errors.fixToken appropriately.
7. Modify StringChecker so that it can output the modifed source and save it to disk. It's simply a loop over the token list, printing the prefix followed by the value of the token.
8. Modify CLI to respect a --fix parameter, which triggers the autoformat option.

@jdlrobson @indexzero help with 1. and 2. would be greatly appreciated.

**Comment by TheSavior** [comment]
@mikesherov, is referencing lines by index a problem? There are also a few rules that are using _operatorIndex.

**Comment by mikesherov** [comment]
@TheSavior, operatorIndex is unrelated. Good question though.

**Comment by soliton4** [comment]
i dont know if this is any help to you but i post it anyway.
nodeMirror has a early version of the formatter integrated now. jscs can also be selected as linter. that way its easy to see how well the formatter works.

let me know if this was helpful

also keep me updated if i should pull a new version of the formatter

**Comment by mdevils** [comment]
Here wo go: #1058

**Comment by mikesherov** [comment]
@mdevils, let's track what's left:

1. Saving file in case of not stdin.
2. Autofixing for validateIndentation.
3. Strategy for non whitespace fixes.
4. Converting remaining rules.

Anything else?

**Comment by TheSavior** [comment]
Can you give an example of a reasonable non whitespace thing we could fix?

**Comment by mikesherov** [comment]
@TheSavior the multipleVarDecl rules. We don't need to solve it now, but we have the come up with something like @gero3's strategy of direct source manipulation followed by AST rebuild or figure out how to manipulate an existing AST.

**Comment by TheSavior** [comment]
My intuition says that all of the iterative solutions we are considering are the easy first approach, but won't be robust long term for all possible 'fixes' rules might want. I would think we need a way to have some sort of engine that understands what the rules are doing and could know if any of the rules conflict. 

At that point, we would be able to take in a parse tree of a file and step through it applying the applicable rules and convert it step by step into actual code.

**Comment by mdevils** [comment]
> 1. Saving file in case of not stdin.

What do you mean? Current implementation saves changes into files.

**Comment by mikesherov** [comment]
I must've missed that!

**Comment by zxqfox** [comment]
> Strategy for non whitespace fixes.

It can be fixing in place if we already doing it in assertion. But I feel like it becomes a mess because of high cyclomatic complexity in some rules.

**Comment by mdevils** [comment]
> 3. Strategy for non whitespace fixes.

I think we can leave this as is and focus on whitespaces first.

**Comment by TheSavior** [comment]
:+1:

**Comment by hzoo** [comment]
Do we have a strategy for `disallowMixedSpacesAndTabs` or `disallowTrailingWhitespace`? Also whitespace related to alignment like `requireAlignedObjectValues`.

Other whitespace rules (should be the last ones)
- [ ] `disallowMultipleLineBreaks`
- [ ] `disallowSpaceAfterLineComment`, `requireSpaceAfterLineComment`
- [ ] `requireLineFeedAtFileEnd`

I'l do a PR for `requireSpaceBeforeKeywords`.

**Comment by millermedeiros** [comment]
so @jzaefferer just told me about the plan to add formatting to jscs. To be really honest, I would love to see someone else solve this problem for me since I'm not having that much time to work on esformatter and have other priorities in life at the moment... but for what I could see you guys are moving towards a dead end and underestimating the complexity of this problem.

Handling white space is the **easiest** part of code formatting by far; adding/removing line breaks is tricky (child nodes affects the parent nodes structure) but indentation is the real challenge; specially if you want to support multiple code formats.

There are many reasons why esformatter works the way it does, and today I added some info [describing how/why we transform and indent the code that way](https://github.com/millermedeiros/esformatter/blob/master/CONTRIBUTING.md#how-it-works); it might be worth the read.

I did not spend too much time looking at how you're implementing the autofix but it looks like most of the rules are line based, if that is really the case you will have a really hard time when you try to add/remove line breaks and implement proper indentation. There are so many edge cases that it's basically impossible to handle it all in a single step (indentation should always be the last step otherwise it **will** be wrong for sure).

I would love if more people contributed to esformatter (fixing what is currently broken) and actually created a plugin to [convert the jscs config file into a format that esformatter can understand](https://github.com/millermedeiros/esformatter/issues/230). I honestly think it would save a lot of headaches to all the people involved.

Nowadays I would even [implement esformatter in a different way](https://twitter.com/millermedeiros/status/569990065478377472) but some changes would require so much work that it is definitely not worth doing (like building a proper CST instead of using an *enhanced* AST).

Until I find something that works better than esformatter, or stop using JavaScript, I'll keep developing it, even if it takes forever to finish... - any help is highly appreciated, pull requests with reduced test cases and bug reports are extremely helpful (code is only as good as the tests).

Good luck!

PS: the using the `assertion` is really the best abstraction that I could think about, it's very similar to how I handle it on esformatter with `ws.limitBefore(token, tokenIdOrValue)` and `ws.limitAfter(token, tokenIdOrValue)` - limiting line breaks is way more complex since you might have comments and white spaces in between but I also abstracted the logic the same way...

**Comment by TheSavior** [comment]
@millermedeiros Not to speak for the rest of the team, but I really appreciate you coming to provide us this context. Having built esformatter, you definitely have some specific understanding that we may not have.

The assertions we use and having that add whitespaceBefore, as you say, seems pretty consistent with how you have things outlined in the file you linked.

Something I didn't quite get from your document explaining how esformatter tokenizes and how you guys transform, are specific examples.

I'd love to get some more understanding and specific examples that you've run into issues with once we try to tackle indentation. I don't believe we have taken any steps in that direction yet.

**Comment by millermedeiros** [comment]
@TheSavior there are a lot of edge cases related to indentation, specially for complex nodes like [IfStatement](https://github.com/millermedeiros/esformatter/blob/master/test/compare/default/if_statement-out.js), [FunctionExpression](https://github.com/millermedeiros/esformatter/blob/master/test/compare/default/function_expression-out.js) and [CallExpression](https://github.com/millermedeiros/esformatter/blob/master/test/compare/default/call_expression-out.js)

There is also the problem of chained member expressions and how they should be handled, specially if you think about the jQuery style guide when [special methods cause negative indents](http://contribute.jquery.org/style-guide/js/#chained-method-calls)...

There are some crazy rules about what should be start/end of the indentation in some cases, specially since we might have optional parenthesis and curly braces...

I'm nailing down one bug at a time, but some problems are very hard to solve if all you have is the line number and/or a vague AST structure. In many cases you need to understand the actual code context and work around the AST limitations.

**Comment by millermedeiros** [comment]
@TheSavior our token list is a LinkedList and not an Array, so it's very trivial to add/remove items in between (we don't use the context of indexes.. we just edit the LinkedList in place) - every token have a reference to the `prev` and `next` tokens, so to add/remove you just need to update the references to `prev/next` on the adjacent sibling tokens. Every node on the AST also have a reference to the `startToken` and `endToken` to make it easier to traverse.

**Comment by mikesherov** [comment]
@millermedeiros, you're welcome to help help us solve the problem here in JSCS just as much as we're able to help you in esformatter. I appreciate the concern about the dead end, but I think it's most unfounded if you haven't taken the time to read all we've said about it on our mailing list and in our various issues. If you're truly interested in having someone else solve the problem, and think that esformatters current impl is suboptimal, we should work together here in JSCS to get this done. In regard to specific critiques:

Linked list for token insertion is a must. We just aren't there yet. Our abstraction makes it pretty trivial to add when we finally tackle that problem. Note that we're also working with Esprima and the estree project to attempt to move forward the CST at some point soon so that something like rocambole or what we do now (basically the same work) is available directly from an esprima parse. 

As far as indentation goes, I think I have a pretty good grasp on the edge cases, and I'd invite you to read what my existing pull request for autofixing indentation tries to accomplish. It has matured over a long period of time and is fairly lenient in what it enforces. Would love *specific* feedback there.

**Comment by mikesherov** [comment]
@millermedeiros, I'd also like to mention that the negative indentation problem for chained method calls is one of concern but is literally no different then any something like switch/case indentation. 

Again, I'd invite you to check out our validateIndentation rule and see how it works before you dismiss it.

With regards to having to do indentation last, that's also a bridge that we may have to come to, but I doubt it. As long as the rules that modify number of lines preserve indentation, it shouldn't matter. But again, we'll see when we get there, and I think JSCS's infra is robust enough to handle that chabge should it be needed to do it last (which is something I suspected, but am not convinced).

**Comment by mikesherov** [comment]
@millermedeiros, lastly, I want to just say that personally, we could use your help on JSCS. Is love for us to consider merging the two projects.

No one is telling you to give up on esformatter, and you should continue working on it to your heart's content, but I've seen you express doubt to as to its design and lament its pace of development.

We've tried to build an inclusive, contributor friendly codebase here, and I think JSCS's momentum and contributor base make it the project we should all be working on instead of in esformatter.

Again, you're welcome to do whatever you like, and we appreciate the input and feedback you've given us, so even if you decide to continue developing esformatter into the foreseeable future, no big deal. But I think we could solve more problems together rather than apart and I think JSCS is in a better place at the moment to handle the task. Of course, I could just be biased.

Let me know what you think.

**Comment by millermedeiros** [comment]
@mikesherov I feel glad for the invite to help on jscs and join forces but I will probably just keep working on esformatter instead. Time is a very limited resource and there are different user needs to be filled.

The design flaw I regret most on esformatter is that I should have built a real CST since the beginning with good helpers for code manipulation; making sure that the CST was as easy as possible to modify (giving more power to plugin authors) and with saner node boundaries - having to search for all the tokens is cumbersome and parenthesis makes things weirder. The main reason why I did this way was because I thought that the tool would only handle white spaces and line breaks, but current plugins are showing that people actually want it to fix other issues as well (quotes, braces, semicolon, etc). I should have also delegated more work to plugins and/or separate libs since the beginning. - jscs structure is no different from that and while you implement code formatting it should become even more similar (eg. start using linked lists).

We are basically approaching the problem starting from 2 *opposite* directions - I was initially thinking about writing a tool that does basic string diff between esformatter input/output to validate the code style, while jscs uses the validation to correct the differences...

I'm confident you guys will find a solution to all the problems given enough time, just wanted to give a *heads up*; keep the good work!

PS:  Maybe this idea of having a *competitor* will motivate me to move faster :D

**Comment by mikesherov** [comment]
@millermedeiros thanks for the thoughtful reply. At the very least, perhaps you can help contribute to the CST discussion in the estree repo once that gets underway... as the atuhor of Rocambole, your input is invaluable there.

**Comment by millermedeiros** [comment]
FYI I resumed esformatter development and closed 20 issues this week (all the reported bugs that we had) and just published [v0.5.0 to npm](https://www.npmjs.com/package/esformatter). v0.6 is coming soon with lots of improvements. I promise I won't spam in the next releases, just thought it was a good idea to share in case you guys change your minds and decide to reuse it (or at least decide to borrow some of the test cases). cheers.

**Comment by mikesherov** [comment]
Congrats. Good luck with the continued development of your project.

**Comment by TheSavior** [comment]
I just put up a sublime plugin that uses the globally installed JSCS version to autoformat your code. 

https://github.com/TheSavior/Sublime-JSCS-Formatter

I'm going through the process to get it added to Sublime's Package Manager right now: https://github.com/wbond/package_control_channel/pull/4148

**Comment by varemenos** [comment]
@TheSavior you truly are the savior :)

**Comment by mikesherov** [comment]
@TheSavior, awesome work! Would you mind waiting until 1.12 is released before submitting that package? I wouldn't want users to get confused.

**Comment by TheSavior** [comment]
@mikesherov Sure thing. This is my first sublime plugin and I really have no idea what I'm doing, so I wanted to jump through the hoops now to get things cleaned up.

If any of you use sublime and know python or want to explore the world of plugins, I would really appreciate any pull requests people have time for. :)

**Comment by indexzero** [comment]
@mikesherov looks like great progress here! I read the comments a bit and saw all the referenced commits for each rule 👍

... is there a place listing all the rules and which ones still need autofixing added? A checklist somewhere would be super helpful. I've finally got a little time and would love to pinch hit and knock a few out.

**Comment by markelog** [comment]
@indexzero only whitespace, eof and indentation rules are supported at the moment, there is no clear way to support others, more specific rules like `disallowAnonymousFunctions` or `disallowCommaBeforeLineBreak`, etc.

Right know, we thinking, either specific assertions for every rule or <a href="https://github.com/jscs-dev/node-jscs/issues/1113">this</a>.

**Comment by mikesherov** [comment]
@indexzero disallowMultipleLineBreaks still needs conversion. 

Also, the `(no)whiteSpaceBetween` rule need to be fixed so that if a comment token exists between the two provided tokens, don't attempt to autofix. See the linesBetween rules for prior art there.

If you can get PR's going for that, I think we're in a fairly good place, and can discuss releasing 1.13, which has the goal of fixing whitespace only.

**Comment by mikesherov** [comment]
@indexzero also discovered `requireAlignedObjectValues` needs conversion as well.

**Comment by TheSavior** [comment]
Are changing those 4 rules all that is left before releasing 1.13?

**Comment by markelog** [comment]
Autofix has been landed, other updates will be iterative, so if no one object, i would like to close this one. Will wait until tomorrow.

As a team, we decided to donate this money to charity organization "Girls Who Code" - https://girlswhocode.com.

Thank you everyone!

**Comment by zxqfox** [comment]
Great news everyone :+1:

**Comment by soliton4** [comment]
i agree

is there a api documentation available yet?

**Comment by zxqfox** [comment]
@soliton4 Docs in progress: #1231 #1192

There are the very first try also: #1202

**Comment by difosfor** [comment]
Experimenting with this in our build tool and very excited about the possibilities! But now of course we want more ;)

What about non-whitespace fixing? I imagine/hope it shouldn't be too hard to fix errors related to comma's and semi-colons. E.g: anything where the error message is already pointing exactly at where a certain character is missing or should not be.

Are you guys working on this already and should we just add some bounty and/or how can I contribute?

PS: Personally I disagree with people who would like to see this developed in a separate project. Fixing is a core feature. Having software tell you exactly what you did wrong and then subsequently not helping you save time by fixing it seems a bit masochistic to me. It's just like an annoying teacher who keeps hitting you on your fingers every time you make a mistake instead of an assistant that smoothes things out for you.

**Comment by zxqfox** [comment]
@dfilatov #1202 — I think the battle begins ;-)

**Comment by markelog** [comment]
@difosfor https://github.com/jscs-dev/node-jscs/issues/1113 has potential, but there is concern of providing API for modifying AST, since there is obvious danger in that way.

We have this - https://github.com/jscs-dev/node-jscs/issues/1086 as at least one element of protection from ruining your code. 

We need to be very careful here.

**Comment by mrjoelkemp** [comment]
@markelog can we close this?

**Comment by mrjoelkemp** [comment]
This solution was worked on by many individuals in the community. Together, we have decided that the bounty should go to charity: https://groups.google.com/forum/#!topic/jscs-dev/u-Gy0Yh97EU. 

As a core team member, I was nominated to handle claiming the bounty, donating the money, and posting a donation receipt on the issue to notify the community of the donation. I will post status updates on this issue to stay transparent until the donation receipt is posted. 

To start the claiming of the bounty, I need to close the ticket.

**Comment by mrjoelkemp** [comment]
![image](https://cloud.githubusercontent.com/assets/865203/7631574/0334db90-fa12-11e4-9ebf-49b951bcc9e3.png)

> The bounty will be paid out if all backers accept your claim or if no backers reject your claim by May 28, 2015 8:19 AM (GMT).

I'll check bountysource on the 28th (or sooner if all backers accept the claim) to proceed with the next steps.

**Comment by mrjoelkemp** [comment]
The bounty was awarded.

![image](https://cloud.githubusercontent.com/assets/865203/7860290/b7b95aa6-0515-11e5-9c41-74c9da089426.png)

I've requested to be paid via paypal. 

![image](https://cloud.githubusercontent.com/assets/865203/7860286/ad683478-0515-11e5-9026-9f5d4d26e13b.png)

Bountysource took a $31 cut from the funds. That left a balance of 284 (315 - 31).

**Comment by indexzero** [comment]
👍💪🙌

**Comment by mrjoelkemp** [comment]
![image](https://cloud.githubusercontent.com/assets/865203/7871065/712b03aa-055b-11e5-9b33-16081e2411b9.png)

Getting it transferred to my bank and will then donate that money. Everyone wants a cut of the funds, it seems. Not even charity gets a break from fees!

Will post a donation receipt once that's done.

**Comment by mrjoelkemp** [comment]
Just a quick update. The money has reached my account. I'll donate it on Wednesday and post a receipt.

**Comment by mrjoelkemp** [comment]
Donation complete. Thanks again to everyone who contributed to the effort.

![donation](https://cloud.githubusercontent.com/assets/865203/8083451/a3fb8bdc-0f52-11e5-9526-64b569eebab5.jpg)
