### ISSUE TITLE
improve of finding .jscsrc behavior

### ISSUE THREAD

**Issue by golyshevd** [jscs-dev/node-jscs#559]
Hi! In our project we need to use more than one codestyles. We tried to put ```.jscsrc``` in subdirectory where used another than default codestyle

```
/.jscsrc
/other-code-style/
    my-file.js
    .jscsrc
```
```js
checker.checkFile('./other-code-style/my-file.js');
```

But jscs finds ```.jscsrc``` up from cwd or from passed directory, not from filePath. And we had to use the second call of jscs for ```other-code-style``` directory. In my opinion jscs should use ```other-code-style/.jscsrc``` file for ```other-code-style/my-file.js```.

I understand that it is too expensive to find .jscsrc for each checkFile call, but isn't that native behavior?

**Comment by hzoo** [comment]
We released [3.0](https://github.com/jscs-dev/node-jscs/releases/tag/v3.0.0) recently! We also wrote a [post](https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.oot3wvgpu) about how 3.0 will be our last major release (since we are deprecating the project) and that we are [merging with ESLint](http://eslint.org/blog/2016/04/welcoming-jscs-to-eslint)!

Thus we won't be working on any new features moving forward which includes new rules/options. We will continue to fix bugs and work on CST/better autofixing for current rules in the upcoming months both to help JSCS users and to gain experience that we can hopefully use in ESLint. But otherwise we both teams will be working on getting [ESLint feature parity with JSCS](https://github.com/eslint/eslint/milestones/JSCS%20Compatibility) and just a nice transition for our users.

I'm putting an `orphaned` label to note this issue isn't planned to be worked on.
