### ISSUE TITLE
Esprima 2.0 (mainly for ES6)

### ISSUE THREAD

**Issue by MoOx** [jscs-dev/node-jscs#561]
Can this issue should remain open until esprima 2.0 is integrated here ?
So people can track status of jscs + es6 (I've some es6 project I would love to "validate" with jscs) ?
[ref](https://github.com/mdevils/node-jscs/issues/441#issuecomment-51769365)

Feel free to update/rename this ticket :)

**Comment by malandrew** [comment]
Now that the official 2.0 esprima branch has been released (with official ES6 support for some features) can it be used instead of the harmony branch (which may have more comprehensive ES6 support today, but is poorly documented)?

**Comment by mrjoelkemp** [comment]
@malandrew The `--esprima` option should work: http://jscs.info/overview.html

**Comment by mikesherov** [comment]
@malandrew, for now, Esprima 2.0 has only bits of es6 support, so not yet suitable for the --esnext option.

Very quickly though, the es6 stuff will continue to land and when is fully implemented, will make the --esnext flag only modify certain rules rather than switch parsers.

There's nothing to do here except fix bugs in ESPrima harmony so it can be merged into master.
