### ISSUE TITLE
Standardise terminology around line-break, line-feed or newline

### ISSUE THREAD

**Issue by Krinkle** [jscs-dev/node-jscs#853]
```
requireLineBreakAfterVariableAssignment
require-line-break-after-variable-assignment.js

requireLineFeedAtFileEnd
require-line-feed-at-file-end.js

requireNewlineBeforeBlockStatements
require-newline-before-block-statements.js
```

Let's pick one and stick to it.

**Comment by jasonkarns** [comment]
Related to standardizing on line break, line feed, or newline since it seems that `newline` will be the standard; the capitalization needs to be standardized as well.

Presently, there are 13 rules that capitalize newline as `NewLine`:
```
(require/disallow)KeywordsOnNewLine
(require/disallow)PaddingNewLinesAfterBlocks
(require/disallow)PaddingNewLinesAfterUseStrict
(require/disallow)PaddingNewLinesBeforeExport
(require/disallow)PaddingNewLinesBeforeLineComments
(require/disallow)PaddingNewLinesInObjects
requirePaddingNewLineAfterVariableDeclaration
```

and 8 rules that caplitalize it as `Newline`:
```
(require/disallow)NewlineBeforeBlockStatements
(require/disallow)PaddingNewlinesBeforeKeywords
(require/disallow)PaddingNewlinesInBlocks
requireBlocksOnNewline
validateNewlineAfterArrayElements
```

Personally, I consider a newline to be a standalone noun these days so I would vote for `Newline`. As opposed to the adjective-noun phrase 'new line' which would lend itself to capitalizing each word in the phrase separately as `NewLine`. But having a consistent spelling is more important that which form is chosen.

**Comment by hzoo** [comment]
Moving to #1834 (hopefully doing it correctly)
