### ISSUE TITLE
disallowSpacesInCallExpression for class instantiation

### ISSUE THREAD

**Issue by gagle** [jscs-dev/node-jscs#898]
`disallowSpacesInCallExpression` makes invalid `foo ()`, but a warning is not displayed for `new Foo ()`.

How can I disallow spaces between the constructor and parenthesis when using `new`?

**Comment by mrjoelkemp** [comment]
Hi @gagle. Thanks for contributing. The reason is that `new Foo()` is not a `CallExpression`, it's a `NewExpression`. 

Making this as a configurable exception for the rule seems to be a stretch. A new rule might be more appropriate; though the implementation for disallowSpacesInCallExpression could serve as a helpful basis.

Would you like to give the implementation a go? We could use the help.

**Comment by mikesherov** [comment]
@mrjoelkemp, might make sense to add newExpressions to this rule, despite it not being technically correct because I can't imagine someone wanting spaces in one and not the other.

Only caveat is to not throw an error when new is used without parens, e.g. `var a = new IHateParentheses;`

**Comment by mrjoelkemp** [comment]
Sounds good. Perhaps this can be considered a bug from a user's standpoint?

**Comment by mikesherov** [comment]
Sure, but different rule. If newExpression has no parens, this particular rule is silent. We can always add `require|disallowParenthesesAfterNewExpression`.
