### ISSUE TITLE
`disallowKeywordsOnNewLine` reports "else" erroneously when not in a block statement.

### ISSUE THREAD

**Issue by mikesherov** [jscs-dev/node-jscs#905]
```
keyyword `else` should not be placed on new line at src/jshint.js :
  1913 |        case "unused":
  1914 |          if (block) block[v]["(type)"] = "var";
  1915 |          else funct[v] = "var";
```

**Comment by markelog** [comment]
Well, technically it's should show a error just like description for the name suggest

> Disallows placing keywords on a new line.

But i guess we can special case it, since it makes more sense that way.

**Comment by markelog** [comment]
Couple notes: 

1. It seems we don't need to "fix" that for opposite rule
2. I know one other case when braces are optional: `do...while` (is there more?), but if that rule is activated for `while` keyword it will also catch precondition loop too, since it does not distinguishes those cases, so no special case for it.
